global using Vanara.PInvoke;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using static Vanara.PInvoke.Kernel32;
global using static Vanara.PInvoke.User32;
global using static Vanara.PInvoke.NtDll;
global using Vanara;
global using Serilog;
global using Task = System.Threading.Tasks.Task;
global using GC = System.GC;